name: streamlit-env
channels:
  - conda-forge
dependencies:
  - python=3.10  # Use Python 3.10 as specified
  - streamlit=1.26.0
  - pandas=2.2.2
  - numpy=1.23.5
  - opencv-python=4.10.0  # Use headless version for non-GUI environments
  - scikit-learn=1.5.1
  - imutils=0.5.4
  - joblib=1.2.0
  - setuptools>=45.0.0
  - dlib=19.24.0

