name: streamlit-env
channels:
  - conda-forge
dependencies:
  - python=3.10  # Use Python 3.10 as specified
  - scikit-learn=1.2.2  # Compatible with numpy 1.23.5
  - imutils=0.5.4
  - joblib=1.2.0
  - setuptools>=45.0.0
  - dlib=19.24.0
  - pip:
      - opencv-python-headless==4.7.0.72
